version: "3.10"

services:
  app:
    container_name: srcbot
    build: .
    command: bash bash.sh
    environment:
      API_ID: # Your API HASH from my.telegram.org
      API_HASH: # Your API ID from my.telegram.org
      BOT_TOKEN: # Bot token, get it from @BotFather
      DROPLINK_API: # Your droplink API ID
      MDISK_API: # Your MDISK API
      ADMINS: # Your telegram ID
      DATABASE_NAME: # Your mongodb DATABASE NAME
      DATABASE_URL: # Your mongodb DATABASE URL
      WEBSITE: # Your url shortner WEBSITE link
      CHANNEL_ID: # Your telegram CHANNEL ID
      
